# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: Checks

on:
  # Run on pushes to main and dev
  push: 
    branches: [ main, dev ]
  # Run on pull requests to main and dev
  pull_request:
    branches: [ main, dev]

# Cancel any in progress run of the workflow for a given PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Run eslint
        run: npm run lint
  unit-tests:
    name: Unit
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - name: Install dependencies
        run: npm ci
      - name: Run jest
        run: npm run test
